java -classpath ./bin Sili < test01.sil
java -classpath ./bin Sili < test02.sil
java -classpath ./bin Sili < test03.sil
java -classpath ./bin Sili < test04.sil
java -classpath ./bin Sili < test05.sil
java -classpath ./bin Sili < test06.sil
java -classpath ./bin Sili < test07.sil
java -classpath ./bin Sili < test08.sil
java -classpath ./bin Sili < test09.sil
java -classpath ./bin Sili < test10.sil
java -classpath ./bin Sili < test11.sil
java -classpath ./bin Sili < test12.sil
java -classpath ./bin Sili < test13.sil
java -classpath ./bin Sili < test14.sil
java -classpath ./bin Sili < test15.sil
java -classpath ./bin Sili < test16.sil
java -classpath ./bin Sili < test17.sil
java -classpath ./bin Sili < test18.sil
java -classpath ./bin Sili < test19.sil