java -classpath ./bin CScharf < test01.csf
java -classpath ./bin CScharf < test02.csf
java -classpath ./bin CScharf < test03.csf
java -classpath ./bin CScharf < test04.csf
java -classpath ./bin CScharf < test05.csf
java -classpath ./bin CScharf < test06.csf
java -classpath ./bin CScharf < test07.csf
java -classpath ./bin CScharf < test08.csf
java -classpath ./bin CScharf < test09.csf
java -classpath ./bin CScharf < test10.csf
java -classpath ./bin CScharf < test11.csf
java -classpath ./bin CScharf < test12.csf
java -classpath ./bin CScharf < test13.csf
java -classpath ./bin CScharf < test14.csf
java -classpath ./bin CScharf < test15.csf
java -classpath ./bin CScharf < test16.csf
java -classpath ./bin CScharf < test17.csf
java -classpath ./bin CScharf < test18.csf
java -classpath ./bin CScharf < test19.csf
java -classpath ./bin CScharf < test20.csf
java -classpath ./bin CScharf < test21.csf
java -classpath ./bin CScharf < test22.csf
java -classpath ./bin CScharf < test23.csf
java -classpath ./bin CScharf < test24.csf
java -classpath ./bin CScharf < test25.csf
java -classpath ./bin CScharf < test26.csf